// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ExternalServiceURL is an object representing the database table.
type ExternalServiceURL struct {
	ID          string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	URL         string    `boil:"url" json:"url" toml:"url" yaml:"url"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt   null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	UserID      string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ServiceType int       `boil:"service_type" json:"service_type" toml:"service_type" yaml:"service_type"`

	R *externalServiceURLR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L externalServiceURLL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ExternalServiceURLColumns = struct {
	ID          string
	URL         string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
	UserID      string
	ServiceType string
}{
	ID:          "id",
	URL:         "url",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
	UserID:      "user_id",
	ServiceType: "service_type",
}

var ExternalServiceURLTableColumns = struct {
	ID          string
	URL         string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
	UserID      string
	ServiceType string
}{
	ID:          "external_service_urls.id",
	URL:         "external_service_urls.url",
	CreatedAt:   "external_service_urls.created_at",
	UpdatedAt:   "external_service_urls.updated_at",
	DeletedAt:   "external_service_urls.deleted_at",
	UserID:      "external_service_urls.user_id",
	ServiceType: "external_service_urls.service_type",
}

// Generated where

var ExternalServiceURLWhere = struct {
	ID          whereHelperstring
	URL         whereHelperstring
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
	DeletedAt   whereHelpernull_Time
	UserID      whereHelperstring
	ServiceType whereHelperint
}{
	ID:          whereHelperstring{field: "`external_service_urls`.`id`"},
	URL:         whereHelperstring{field: "`external_service_urls`.`url`"},
	CreatedAt:   whereHelpertime_Time{field: "`external_service_urls`.`created_at`"},
	UpdatedAt:   whereHelpertime_Time{field: "`external_service_urls`.`updated_at`"},
	DeletedAt:   whereHelpernull_Time{field: "`external_service_urls`.`deleted_at`"},
	UserID:      whereHelperstring{field: "`external_service_urls`.`user_id`"},
	ServiceType: whereHelperint{field: "`external_service_urls`.`service_type`"},
}

// ExternalServiceURLRels is where relationship names are stored.
var ExternalServiceURLRels = struct {
	User string
}{
	User: "User",
}

// externalServiceURLR is where relationships are stored.
type externalServiceURLR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*externalServiceURLR) NewStruct() *externalServiceURLR {
	return &externalServiceURLR{}
}

func (r *externalServiceURLR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// externalServiceURLL is where Load methods for each relationship are stored.
type externalServiceURLL struct{}

var (
	externalServiceURLAllColumns            = []string{"id", "url", "created_at", "updated_at", "deleted_at", "user_id", "service_type"}
	externalServiceURLColumnsWithoutDefault = []string{"id", "url", "deleted_at", "user_id", "service_type"}
	externalServiceURLColumnsWithDefault    = []string{"created_at", "updated_at"}
	externalServiceURLPrimaryKeyColumns     = []string{"id"}
	externalServiceURLGeneratedColumns      = []string{}
)

type (
	// ExternalServiceURLSlice is an alias for a slice of pointers to ExternalServiceURL.
	// This should almost always be used instead of []ExternalServiceURL.
	ExternalServiceURLSlice []*ExternalServiceURL
	// ExternalServiceURLHook is the signature for custom ExternalServiceURL hook methods
	ExternalServiceURLHook func(context.Context, boil.ContextExecutor, *ExternalServiceURL) error

	externalServiceURLQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	externalServiceURLType                 = reflect.TypeOf(&ExternalServiceURL{})
	externalServiceURLMapping              = queries.MakeStructMapping(externalServiceURLType)
	externalServiceURLPrimaryKeyMapping, _ = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, externalServiceURLPrimaryKeyColumns)
	externalServiceURLInsertCacheMut       sync.RWMutex
	externalServiceURLInsertCache          = make(map[string]insertCache)
	externalServiceURLUpdateCacheMut       sync.RWMutex
	externalServiceURLUpdateCache          = make(map[string]updateCache)
	externalServiceURLUpsertCacheMut       sync.RWMutex
	externalServiceURLUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var externalServiceURLAfterSelectMu sync.Mutex
var externalServiceURLAfterSelectHooks []ExternalServiceURLHook

var externalServiceURLBeforeInsertMu sync.Mutex
var externalServiceURLBeforeInsertHooks []ExternalServiceURLHook
var externalServiceURLAfterInsertMu sync.Mutex
var externalServiceURLAfterInsertHooks []ExternalServiceURLHook

var externalServiceURLBeforeUpdateMu sync.Mutex
var externalServiceURLBeforeUpdateHooks []ExternalServiceURLHook
var externalServiceURLAfterUpdateMu sync.Mutex
var externalServiceURLAfterUpdateHooks []ExternalServiceURLHook

var externalServiceURLBeforeDeleteMu sync.Mutex
var externalServiceURLBeforeDeleteHooks []ExternalServiceURLHook
var externalServiceURLAfterDeleteMu sync.Mutex
var externalServiceURLAfterDeleteHooks []ExternalServiceURLHook

var externalServiceURLBeforeUpsertMu sync.Mutex
var externalServiceURLBeforeUpsertHooks []ExternalServiceURLHook
var externalServiceURLAfterUpsertMu sync.Mutex
var externalServiceURLAfterUpsertHooks []ExternalServiceURLHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ExternalServiceURL) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ExternalServiceURL) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ExternalServiceURL) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ExternalServiceURL) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ExternalServiceURL) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ExternalServiceURL) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ExternalServiceURL) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ExternalServiceURL) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ExternalServiceURL) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalServiceURLAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExternalServiceURLHook registers your hook function for all future operations.
func AddExternalServiceURLHook(hookPoint boil.HookPoint, externalServiceURLHook ExternalServiceURLHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		externalServiceURLAfterSelectMu.Lock()
		externalServiceURLAfterSelectHooks = append(externalServiceURLAfterSelectHooks, externalServiceURLHook)
		externalServiceURLAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		externalServiceURLBeforeInsertMu.Lock()
		externalServiceURLBeforeInsertHooks = append(externalServiceURLBeforeInsertHooks, externalServiceURLHook)
		externalServiceURLBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		externalServiceURLAfterInsertMu.Lock()
		externalServiceURLAfterInsertHooks = append(externalServiceURLAfterInsertHooks, externalServiceURLHook)
		externalServiceURLAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		externalServiceURLBeforeUpdateMu.Lock()
		externalServiceURLBeforeUpdateHooks = append(externalServiceURLBeforeUpdateHooks, externalServiceURLHook)
		externalServiceURLBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		externalServiceURLAfterUpdateMu.Lock()
		externalServiceURLAfterUpdateHooks = append(externalServiceURLAfterUpdateHooks, externalServiceURLHook)
		externalServiceURLAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		externalServiceURLBeforeDeleteMu.Lock()
		externalServiceURLBeforeDeleteHooks = append(externalServiceURLBeforeDeleteHooks, externalServiceURLHook)
		externalServiceURLBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		externalServiceURLAfterDeleteMu.Lock()
		externalServiceURLAfterDeleteHooks = append(externalServiceURLAfterDeleteHooks, externalServiceURLHook)
		externalServiceURLAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		externalServiceURLBeforeUpsertMu.Lock()
		externalServiceURLBeforeUpsertHooks = append(externalServiceURLBeforeUpsertHooks, externalServiceURLHook)
		externalServiceURLBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		externalServiceURLAfterUpsertMu.Lock()
		externalServiceURLAfterUpsertHooks = append(externalServiceURLAfterUpsertHooks, externalServiceURLHook)
		externalServiceURLAfterUpsertMu.Unlock()
	}
}

// One returns a single externalServiceURL record from the query.
func (q externalServiceURLQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ExternalServiceURL, error) {
	o := &ExternalServiceURL{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for external_service_urls")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ExternalServiceURL records from the query.
func (q externalServiceURLQuery) All(ctx context.Context, exec boil.ContextExecutor) (ExternalServiceURLSlice, error) {
	var o []*ExternalServiceURL

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ExternalServiceURL slice")
	}

	if len(externalServiceURLAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ExternalServiceURL records in the query.
func (q externalServiceURLQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count external_service_urls rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q externalServiceURLQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if external_service_urls exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *ExternalServiceURL) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (externalServiceURLL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExternalServiceURL interface{}, mods queries.Applicator) error {
	var slice []*ExternalServiceURL
	var object *ExternalServiceURL

	if singular {
		var ok bool
		object, ok = maybeExternalServiceURL.(*ExternalServiceURL)
		if !ok {
			object = new(ExternalServiceURL)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExternalServiceURL)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExternalServiceURL))
			}
		}
	} else {
		s, ok := maybeExternalServiceURL.(*[]*ExternalServiceURL)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExternalServiceURL)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExternalServiceURL))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &externalServiceURLR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &externalServiceURLR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ExternalServiceUrls = append(foreign.R.ExternalServiceUrls, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ExternalServiceUrls = append(foreign.R.ExternalServiceUrls, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the externalServiceURL to the related item.
// Sets o.R.User to related.
// Adds o to related.R.ExternalServiceUrls.
func (o *ExternalServiceURL) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `external_service_urls` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, externalServiceURLPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &externalServiceURLR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			ExternalServiceUrls: ExternalServiceURLSlice{o},
		}
	} else {
		related.R.ExternalServiceUrls = append(related.R.ExternalServiceUrls, o)
	}

	return nil
}

// ExternalServiceUrls retrieves all the records using an executor.
func ExternalServiceUrls(mods ...qm.QueryMod) externalServiceURLQuery {
	mods = append(mods, qm.From("`external_service_urls`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`external_service_urls`.*"})
	}

	return externalServiceURLQuery{q}
}

// FindExternalServiceURL retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExternalServiceURL(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ExternalServiceURL, error) {
	externalServiceURLObj := &ExternalServiceURL{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `external_service_urls` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, externalServiceURLObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from external_service_urls")
	}

	if err = externalServiceURLObj.doAfterSelectHooks(ctx, exec); err != nil {
		return externalServiceURLObj, err
	}

	return externalServiceURLObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ExternalServiceURL) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no external_service_urls provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(externalServiceURLColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	externalServiceURLInsertCacheMut.RLock()
	cache, cached := externalServiceURLInsertCache[key]
	externalServiceURLInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			externalServiceURLAllColumns,
			externalServiceURLColumnsWithDefault,
			externalServiceURLColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `external_service_urls` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `external_service_urls` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `external_service_urls` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, externalServiceURLPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into external_service_urls")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for external_service_urls")
	}

CacheNoHooks:
	if !cached {
		externalServiceURLInsertCacheMut.Lock()
		externalServiceURLInsertCache[key] = cache
		externalServiceURLInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ExternalServiceURL.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ExternalServiceURL) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	externalServiceURLUpdateCacheMut.RLock()
	cache, cached := externalServiceURLUpdateCache[key]
	externalServiceURLUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			externalServiceURLAllColumns,
			externalServiceURLPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update external_service_urls, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `external_service_urls` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, externalServiceURLPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, append(wl, externalServiceURLPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update external_service_urls row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for external_service_urls")
	}

	if !cached {
		externalServiceURLUpdateCacheMut.Lock()
		externalServiceURLUpdateCache[key] = cache
		externalServiceURLUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q externalServiceURLQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for external_service_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for external_service_urls")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExternalServiceURLSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalServiceURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `external_service_urls` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, externalServiceURLPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in externalServiceURL slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all externalServiceURL")
	}
	return rowsAff, nil
}

var mySQLExternalServiceURLUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ExternalServiceURL) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no external_service_urls provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(externalServiceURLColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLExternalServiceURLUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	externalServiceURLUpsertCacheMut.RLock()
	cache, cached := externalServiceURLUpsertCache[key]
	externalServiceURLUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			externalServiceURLAllColumns,
			externalServiceURLColumnsWithDefault,
			externalServiceURLColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			externalServiceURLAllColumns,
			externalServiceURLPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert external_service_urls, could not build update column list")
		}

		ret := strmangle.SetComplement(externalServiceURLAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`external_service_urls`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `external_service_urls` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for external_service_urls")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(externalServiceURLType, externalServiceURLMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for external_service_urls")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for external_service_urls")
	}

CacheNoHooks:
	if !cached {
		externalServiceURLUpsertCacheMut.Lock()
		externalServiceURLUpsertCache[key] = cache
		externalServiceURLUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ExternalServiceURL record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ExternalServiceURL) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ExternalServiceURL provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), externalServiceURLPrimaryKeyMapping)
	sql := "DELETE FROM `external_service_urls` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from external_service_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for external_service_urls")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q externalServiceURLQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no externalServiceURLQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from external_service_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for external_service_urls")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExternalServiceURLSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(externalServiceURLBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalServiceURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `external_service_urls` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, externalServiceURLPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from externalServiceURL slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for external_service_urls")
	}

	if len(externalServiceURLAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ExternalServiceURL) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindExternalServiceURL(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExternalServiceURLSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ExternalServiceURLSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalServiceURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `external_service_urls`.* FROM `external_service_urls` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, externalServiceURLPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ExternalServiceURLSlice")
	}

	*o = slice

	return nil
}

// ExternalServiceURLExists checks if the ExternalServiceURL row exists.
func ExternalServiceURLExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `external_service_urls` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if external_service_urls exists")
	}

	return exists, nil
}

// Exists checks if the ExternalServiceURL row exists.
func (o *ExternalServiceURL) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ExternalServiceURLExists(ctx, exec, o.ID)
}
