// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Work is an object representing the database table.
type Work struct {
	ID    string `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title string `boil:"title" json:"title" toml:"title" yaml:"title"`
	// 作品の表示順序を管理するインデックス。デフォルトは-1
	SortIndex           int         `boil:"sort_index" json:"sort_index" toml:"sort_index" yaml:"sort_index"`
	CreatedAt           time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt           time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt           null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	UserID              string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	GithubRepositoryURL string      `boil:"github_repository_url" json:"github_repository_url" toml:"github_repository_url" yaml:"github_repository_url"`
	IsDraft             bool        `boil:"is_draft" json:"is_draft" toml:"is_draft" yaml:"is_draft"`
	ThumbnailImageURL   null.String `boil:"thumbnail_image_url" json:"thumbnail_image_url,omitempty" toml:"thumbnail_image_url" yaml:"thumbnail_image_url,omitempty"`
	PublishStatus       string      `boil:"publish_status" json:"publish_status" toml:"publish_status" yaml:"publish_status"`

	R *workR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkColumns = struct {
	ID                  string
	Title               string
	SortIndex           string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
	UserID              string
	GithubRepositoryURL string
	IsDraft             string
	ThumbnailImageURL   string
	PublishStatus       string
}{
	ID:                  "id",
	Title:               "title",
	SortIndex:           "sort_index",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	DeletedAt:           "deleted_at",
	UserID:              "user_id",
	GithubRepositoryURL: "github_repository_url",
	IsDraft:             "is_draft",
	ThumbnailImageURL:   "thumbnail_image_url",
	PublishStatus:       "publish_status",
}

var WorkTableColumns = struct {
	ID                  string
	Title               string
	SortIndex           string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
	UserID              string
	GithubRepositoryURL string
	IsDraft             string
	ThumbnailImageURL   string
	PublishStatus       string
}{
	ID:                  "works.id",
	Title:               "works.title",
	SortIndex:           "works.sort_index",
	CreatedAt:           "works.created_at",
	UpdatedAt:           "works.updated_at",
	DeletedAt:           "works.deleted_at",
	UserID:              "works.user_id",
	GithubRepositoryURL: "works.github_repository_url",
	IsDraft:             "works.is_draft",
	ThumbnailImageURL:   "works.thumbnail_image_url",
	PublishStatus:       "works.publish_status",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var WorkWhere = struct {
	ID                  whereHelperstring
	Title               whereHelperstring
	SortIndex           whereHelperint
	CreatedAt           whereHelpertime_Time
	UpdatedAt           whereHelpertime_Time
	DeletedAt           whereHelpernull_Time
	UserID              whereHelperstring
	GithubRepositoryURL whereHelperstring
	IsDraft             whereHelperbool
	ThumbnailImageURL   whereHelpernull_String
	PublishStatus       whereHelperstring
}{
	ID:                  whereHelperstring{field: "`works`.`id`"},
	Title:               whereHelperstring{field: "`works`.`title`"},
	SortIndex:           whereHelperint{field: "`works`.`sort_index`"},
	CreatedAt:           whereHelpertime_Time{field: "`works`.`created_at`"},
	UpdatedAt:           whereHelpertime_Time{field: "`works`.`updated_at`"},
	DeletedAt:           whereHelpernull_Time{field: "`works`.`deleted_at`"},
	UserID:              whereHelperstring{field: "`works`.`user_id`"},
	GithubRepositoryURL: whereHelperstring{field: "`works`.`github_repository_url`"},
	IsDraft:             whereHelperbool{field: "`works`.`is_draft`"},
	ThumbnailImageURL:   whereHelpernull_String{field: "`works`.`thumbnail_image_url`"},
	PublishStatus:       whereHelperstring{field: "`works`.`publish_status`"},
}

// WorkRels is where relationship names are stored.
var WorkRels = struct {
	User           string
	WorkHavingTags string
	WorkImages     string
	WorkUrls       string
}{
	User:           "User",
	WorkHavingTags: "WorkHavingTags",
	WorkImages:     "WorkImages",
	WorkUrls:       "WorkUrls",
}

// workR is where relationships are stored.
type workR struct {
	User           *User              `boil:"User" json:"User" toml:"User" yaml:"User"`
	WorkHavingTags WorkHavingTagSlice `boil:"WorkHavingTags" json:"WorkHavingTags" toml:"WorkHavingTags" yaml:"WorkHavingTags"`
	WorkImages     WorkImageSlice     `boil:"WorkImages" json:"WorkImages" toml:"WorkImages" yaml:"WorkImages"`
	WorkUrls       WorkURLSlice       `boil:"WorkUrls" json:"WorkUrls" toml:"WorkUrls" yaml:"WorkUrls"`
}

// NewStruct creates a new relationship struct
func (*workR) NewStruct() *workR {
	return &workR{}
}

func (r *workR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *workR) GetWorkHavingTags() WorkHavingTagSlice {
	if r == nil {
		return nil
	}
	return r.WorkHavingTags
}

func (r *workR) GetWorkImages() WorkImageSlice {
	if r == nil {
		return nil
	}
	return r.WorkImages
}

func (r *workR) GetWorkUrls() WorkURLSlice {
	if r == nil {
		return nil
	}
	return r.WorkUrls
}

// workL is where Load methods for each relationship are stored.
type workL struct{}

var (
	workAllColumns            = []string{"id", "title", "sort_index", "created_at", "updated_at", "deleted_at", "user_id", "github_repository_url", "is_draft", "thumbnail_image_url", "publish_status"}
	workColumnsWithoutDefault = []string{"id", "title", "deleted_at", "user_id", "github_repository_url", "thumbnail_image_url"}
	workColumnsWithDefault    = []string{"sort_index", "created_at", "updated_at", "is_draft", "publish_status"}
	workPrimaryKeyColumns     = []string{"id"}
	workGeneratedColumns      = []string{}
)

type (
	// WorkSlice is an alias for a slice of pointers to Work.
	// This should almost always be used instead of []Work.
	WorkSlice []*Work
	// WorkHook is the signature for custom Work hook methods
	WorkHook func(context.Context, boil.ContextExecutor, *Work) error

	workQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workType                 = reflect.TypeOf(&Work{})
	workMapping              = queries.MakeStructMapping(workType)
	workPrimaryKeyMapping, _ = queries.BindMapping(workType, workMapping, workPrimaryKeyColumns)
	workInsertCacheMut       sync.RWMutex
	workInsertCache          = make(map[string]insertCache)
	workUpdateCacheMut       sync.RWMutex
	workUpdateCache          = make(map[string]updateCache)
	workUpsertCacheMut       sync.RWMutex
	workUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workAfterSelectMu sync.Mutex
var workAfterSelectHooks []WorkHook

var workBeforeInsertMu sync.Mutex
var workBeforeInsertHooks []WorkHook
var workAfterInsertMu sync.Mutex
var workAfterInsertHooks []WorkHook

var workBeforeUpdateMu sync.Mutex
var workBeforeUpdateHooks []WorkHook
var workAfterUpdateMu sync.Mutex
var workAfterUpdateHooks []WorkHook

var workBeforeDeleteMu sync.Mutex
var workBeforeDeleteHooks []WorkHook
var workAfterDeleteMu sync.Mutex
var workAfterDeleteHooks []WorkHook

var workBeforeUpsertMu sync.Mutex
var workBeforeUpsertHooks []WorkHook
var workAfterUpsertMu sync.Mutex
var workAfterUpsertHooks []WorkHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Work) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Work) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Work) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Work) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Work) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Work) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Work) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Work) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Work) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkHook registers your hook function for all future operations.
func AddWorkHook(hookPoint boil.HookPoint, workHook WorkHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workAfterSelectMu.Lock()
		workAfterSelectHooks = append(workAfterSelectHooks, workHook)
		workAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workBeforeInsertMu.Lock()
		workBeforeInsertHooks = append(workBeforeInsertHooks, workHook)
		workBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workAfterInsertMu.Lock()
		workAfterInsertHooks = append(workAfterInsertHooks, workHook)
		workAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workBeforeUpdateMu.Lock()
		workBeforeUpdateHooks = append(workBeforeUpdateHooks, workHook)
		workBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workAfterUpdateMu.Lock()
		workAfterUpdateHooks = append(workAfterUpdateHooks, workHook)
		workAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workBeforeDeleteMu.Lock()
		workBeforeDeleteHooks = append(workBeforeDeleteHooks, workHook)
		workBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workAfterDeleteMu.Lock()
		workAfterDeleteHooks = append(workAfterDeleteHooks, workHook)
		workAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workBeforeUpsertMu.Lock()
		workBeforeUpsertHooks = append(workBeforeUpsertHooks, workHook)
		workBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workAfterUpsertMu.Lock()
		workAfterUpsertHooks = append(workAfterUpsertHooks, workHook)
		workAfterUpsertMu.Unlock()
	}
}

// One returns a single work record from the query.
func (q workQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Work, error) {
	o := &Work{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for works")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Work records from the query.
func (q workQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkSlice, error) {
	var o []*Work

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Work slice")
	}

	if len(workAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Work records in the query.
func (q workQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count works rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if works exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Work) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// WorkHavingTags retrieves all the work_having_tag's WorkHavingTags with an executor.
func (o *Work) WorkHavingTags(mods ...qm.QueryMod) workHavingTagQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`work_having_tags`.`work_id`=?", o.ID),
	)

	return WorkHavingTags(queryMods...)
}

// WorkImages retrieves all the work_image's WorkImages with an executor.
func (o *Work) WorkImages(mods ...qm.QueryMod) workImageQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`work_images`.`work_id`=?", o.ID),
	)

	return WorkImages(queryMods...)
}

// WorkUrls retrieves all the work_url's WorkUrls with an executor.
func (o *Work) WorkUrls(mods ...qm.QueryMod) workURLQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`work_urls`.`work_id`=?", o.ID),
	)

	return WorkUrls(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		var ok bool
		object, ok = maybeWork.(*Work)
		if !ok {
			object = new(Work)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWork))
			}
		}
	} else {
		s, ok := maybeWork.(*[]*Work)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWork))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Works = append(foreign.R.Works, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Works = append(foreign.R.Works, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkHavingTags allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workL) LoadWorkHavingTags(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		var ok bool
		object, ok = maybeWork.(*Work)
		if !ok {
			object = new(Work)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWork))
			}
		}
	} else {
		s, ok := maybeWork.(*[]*Work)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWork))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`work_having_tags`),
		qm.WhereIn(`work_having_tags.work_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load work_having_tags")
	}

	var resultSlice []*WorkHavingTag
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice work_having_tags")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on work_having_tags")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for work_having_tags")
	}

	if len(workHavingTagAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkHavingTags = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workHavingTagR{}
			}
			foreign.R.Work = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorkID {
				local.R.WorkHavingTags = append(local.R.WorkHavingTags, foreign)
				if foreign.R == nil {
					foreign.R = &workHavingTagR{}
				}
				foreign.R.Work = local
				break
			}
		}
	}

	return nil
}

// LoadWorkImages allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workL) LoadWorkImages(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		var ok bool
		object, ok = maybeWork.(*Work)
		if !ok {
			object = new(Work)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWork))
			}
		}
	} else {
		s, ok := maybeWork.(*[]*Work)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWork))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`work_images`),
		qm.WhereIn(`work_images.work_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load work_images")
	}

	var resultSlice []*WorkImage
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice work_images")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on work_images")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for work_images")
	}

	if len(workImageAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkImages = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workImageR{}
			}
			foreign.R.Work = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorkID {
				local.R.WorkImages = append(local.R.WorkImages, foreign)
				if foreign.R == nil {
					foreign.R = &workImageR{}
				}
				foreign.R.Work = local
				break
			}
		}
	}

	return nil
}

// LoadWorkUrls allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workL) LoadWorkUrls(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		var ok bool
		object, ok = maybeWork.(*Work)
		if !ok {
			object = new(Work)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWork))
			}
		}
	} else {
		s, ok := maybeWork.(*[]*Work)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWork)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWork))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`work_urls`),
		qm.WhereIn(`work_urls.work_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load work_urls")
	}

	var resultSlice []*WorkURL
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice work_urls")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on work_urls")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for work_urls")
	}

	if len(workURLAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkUrls = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workURLR{}
			}
			foreign.R.Work = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorkID {
				local.R.WorkUrls = append(local.R.WorkUrls, foreign)
				if foreign.R == nil {
					foreign.R = &workURLR{}
				}
				foreign.R.Work = local
				break
			}
		}
	}

	return nil
}

// SetUser of the work to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Works.
func (o *Work) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `works` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, workPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &workR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Works: WorkSlice{o},
		}
	} else {
		related.R.Works = append(related.R.Works, o)
	}

	return nil
}

// AddWorkHavingTags adds the given related objects to the existing relationships
// of the work, optionally inserting them as new records.
// Appends related to o.R.WorkHavingTags.
// Sets related.R.Work appropriately.
func (o *Work) AddWorkHavingTags(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkHavingTag) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `work_having_tags` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"work_id"}),
				strmangle.WhereClause("`", "`", 0, workHavingTagPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workR{
			WorkHavingTags: related,
		}
	} else {
		o.R.WorkHavingTags = append(o.R.WorkHavingTags, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workHavingTagR{
				Work: o,
			}
		} else {
			rel.R.Work = o
		}
	}
	return nil
}

// AddWorkImages adds the given related objects to the existing relationships
// of the work, optionally inserting them as new records.
// Appends related to o.R.WorkImages.
// Sets related.R.Work appropriately.
func (o *Work) AddWorkImages(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkImage) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `work_images` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"work_id"}),
				strmangle.WhereClause("`", "`", 0, workImagePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workR{
			WorkImages: related,
		}
	} else {
		o.R.WorkImages = append(o.R.WorkImages, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workImageR{
				Work: o,
			}
		} else {
			rel.R.Work = o
		}
	}
	return nil
}

// AddWorkUrls adds the given related objects to the existing relationships
// of the work, optionally inserting them as new records.
// Appends related to o.R.WorkUrls.
// Sets related.R.Work appropriately.
func (o *Work) AddWorkUrls(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkURL) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `work_urls` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"work_id"}),
				strmangle.WhereClause("`", "`", 0, workURLPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workR{
			WorkUrls: related,
		}
	} else {
		o.R.WorkUrls = append(o.R.WorkUrls, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workURLR{
				Work: o,
			}
		} else {
			rel.R.Work = o
		}
	}
	return nil
}

// Works retrieves all the records using an executor.
func Works(mods ...qm.QueryMod) workQuery {
	mods = append(mods, qm.From("`works`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`works`.*"})
	}

	return workQuery{q}
}

// FindWork retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWork(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Work, error) {
	workObj := &Work{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `works` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from works")
	}

	if err = workObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workObj, err
	}

	return workObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Work) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no works provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workInsertCacheMut.RLock()
	cache, cached := workInsertCache[key]
	workInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workAllColumns,
			workColumnsWithDefault,
			workColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workType, workMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workType, workMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `works` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `works` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `works` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, workPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into works")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for works")
	}

CacheNoHooks:
	if !cached {
		workInsertCacheMut.Lock()
		workInsertCache[key] = cache
		workInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Work.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Work) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workUpdateCacheMut.RLock()
	cache, cached := workUpdateCache[key]
	workUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workAllColumns,
			workPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update works, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `works` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, workPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workType, workMapping, append(wl, workPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update works row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for works")
	}

	if !cached {
		workUpdateCacheMut.Lock()
		workUpdateCache[key] = cache
		workUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for works")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `works` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in work slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all work")
	}
	return rowsAff, nil
}

var mySQLWorkUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Work) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no works provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLWorkUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workUpsertCacheMut.RLock()
	cache, cached := workUpsertCache[key]
	workUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workAllColumns,
			workColumnsWithDefault,
			workColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workAllColumns,
			workPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert works, could not build update column list")
		}

		ret := strmangle.SetComplement(workAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`works`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `works` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(workType, workMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workType, workMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for works")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(workType, workMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for works")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for works")
	}

CacheNoHooks:
	if !cached {
		workUpsertCacheMut.Lock()
		workUpsertCache[key] = cache
		workUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Work record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Work) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Work provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workPrimaryKeyMapping)
	sql := "DELETE FROM `works` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for works")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for works")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `works` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from work slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for works")
	}

	if len(workAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Work) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWork(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `works`.* FROM `works` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkSlice")
	}

	*o = slice

	return nil
}

// WorkExists checks if the Work row exists.
func WorkExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `works` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if works exists")
	}

	return exists, nil
}

// Exists checks if the Work row exists.
func (o *Work) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkExists(ctx, exec, o.ID)
}
