version: '3'
services:
  web:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true

volumes:
  node_modules:
