// Code generated by MockGen. DO NOT EDIT.
// Source: email_interface.go
//
// Generated by this command:
//
//	mockgen -source=email_interface.go -package=mock_email -destination=../mock/email/email_interface.go
//

// Package mock_email is a generated GoMock package.
package mock_email

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmail is a mock of Email interface.
type MockEmail struct {
	ctrl     *gomock.Controller
	recorder *MockEmailMockRecorder
	isgomock struct{}
}

// MockEmailMockRecorder is the mock recorder for MockEmail.
type MockEmailMockRecorder struct {
	mock *MockEmail
}

// NewMockEmail creates a new mock instance.
func NewMockEmail(ctrl *gomock.Controller) *MockEmail {
	mock := &MockEmail{ctrl: ctrl}
	mock.recorder = &MockEmailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmail) EXPECT() *MockEmailMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmail) SendEmail(to, subject string, vars any, files ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{to, subject, vars}
	for _, a := range files {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailMockRecorder) SendEmail(to, subject, vars any, files ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{to, subject, vars}, files...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmail)(nil).SendEmail), varargs...)
}
