CREATE TABLE users (
  id VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  birthday DATE NOT NULL,
  icon_path VARCHAR(255) DEFAULT '',
  header_path VARCHAR(255) DEFAULT '',
  bio_path VARCHAR(255) DEFAULT '',
  organization_name VARCHAR(255) DEFAULT '',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) DEFAULT NULL,
  INDEX idx_users_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
