# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GoTest

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'back/**'

jobs:
  go_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Domain Test
      run: go test -v ./domain/model

    - name: Usecase Test
      run: go test -v ./usecase/...
