// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBioImages(t *testing.T) {
	t.Parallel()

	query := BioImages()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBioImagesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBioImagesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BioImages().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBioImagesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BioImageSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBioImagesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BioImageExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BioImage exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BioImageExists to return true, but got false.")
	}
}

func testBioImagesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bioImageFound, err := FindBioImage(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if bioImageFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBioImagesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BioImages().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBioImagesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BioImages().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBioImagesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bioImageOne := &BioImage{}
	bioImageTwo := &BioImage{}
	if err = randomize.Struct(seed, bioImageOne, bioImageDBTypes, false, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}
	if err = randomize.Struct(seed, bioImageTwo, bioImageDBTypes, false, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bioImageOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bioImageTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BioImages().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBioImagesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bioImageOne := &BioImage{}
	bioImageTwo := &BioImage{}
	if err = randomize.Struct(seed, bioImageOne, bioImageDBTypes, false, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}
	if err = randomize.Struct(seed, bioImageTwo, bioImageDBTypes, false, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bioImageOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bioImageTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func bioImageBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func bioImageAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BioImage) error {
	*o = BioImage{}
	return nil
}

func testBioImagesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &BioImage{}
	o := &BioImage{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, bioImageDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BioImage object: %s", err)
	}

	AddBioImageHook(boil.BeforeInsertHook, bioImageBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	bioImageBeforeInsertHooks = []BioImageHook{}

	AddBioImageHook(boil.AfterInsertHook, bioImageAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	bioImageAfterInsertHooks = []BioImageHook{}

	AddBioImageHook(boil.AfterSelectHook, bioImageAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	bioImageAfterSelectHooks = []BioImageHook{}

	AddBioImageHook(boil.BeforeUpdateHook, bioImageBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	bioImageBeforeUpdateHooks = []BioImageHook{}

	AddBioImageHook(boil.AfterUpdateHook, bioImageAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	bioImageAfterUpdateHooks = []BioImageHook{}

	AddBioImageHook(boil.BeforeDeleteHook, bioImageBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	bioImageBeforeDeleteHooks = []BioImageHook{}

	AddBioImageHook(boil.AfterDeleteHook, bioImageAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	bioImageAfterDeleteHooks = []BioImageHook{}

	AddBioImageHook(boil.BeforeUpsertHook, bioImageBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	bioImageBeforeUpsertHooks = []BioImageHook{}

	AddBioImageHook(boil.AfterUpsertHook, bioImageAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	bioImageAfterUpsertHooks = []BioImageHook{}
}

func testBioImagesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBioImagesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bioImageColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBioImageToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local BioImage
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, bioImageDBTypes, false, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := BioImageSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*BioImage)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testBioImageToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BioImage
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bioImageDBTypes, false, strmangle.SetComplement(bioImagePrimaryKeyColumns, bioImageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.BioImages[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testBioImagesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBioImagesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BioImageSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBioImagesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BioImages().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bioImageDBTypes = map[string]string{`ID`: `int`, `FileName`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`, `UserID`: `varchar`}
	_               = bytes.MinRead
)

func testBioImagesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bioImagePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bioImageAllColumns) == len(bioImagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBioImagesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bioImageAllColumns) == len(bioImagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BioImage{}
	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bioImageDBTypes, true, bioImagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bioImageAllColumns, bioImagePrimaryKeyColumns) {
		fields = bioImageAllColumns
	} else {
		fields = strmangle.SetComplement(
			bioImageAllColumns,
			bioImagePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BioImageSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBioImagesUpsert(t *testing.T) {
	t.Parallel()

	if len(bioImageAllColumns) == len(bioImagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLBioImageUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BioImage{}
	if err = randomize.Struct(seed, &o, bioImageDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BioImage: %s", err)
	}

	count, err := BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bioImageDBTypes, false, bioImagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BioImage struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BioImage: %s", err)
	}

	count, err = BioImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
