// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BioImages           string
	Certifications      string
	ExternalServiceUrls string
	Skills              string
	Users               string
	WorkHavingTags      string
	WorkImages          string
	WorkTags            string
	WorkUrls            string
	Works               string
}{
	BioImages:           "bio_images",
	Certifications:      "certifications",
	ExternalServiceUrls: "external_service_urls",
	Skills:              "skills",
	Users:               "users",
	WorkHavingTags:      "work_having_tags",
	WorkImages:          "work_images",
	WorkTags:            "work_tags",
	WorkUrls:            "work_urls",
	Works:               "works",
}
