// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testExternalServiceUrls(t *testing.T) {
	t.Parallel()

	query := ExternalServiceUrls()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testExternalServiceUrlsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testExternalServiceUrlsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ExternalServiceUrls().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testExternalServiceUrlsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ExternalServiceURLSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testExternalServiceUrlsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ExternalServiceURLExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ExternalServiceURL exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ExternalServiceURLExists to return true, but got false.")
	}
}

func testExternalServiceUrlsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	externalServiceURLFound, err := FindExternalServiceURL(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if externalServiceURLFound == nil {
		t.Error("want a record, got nil")
	}
}

func testExternalServiceUrlsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ExternalServiceUrls().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testExternalServiceUrlsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ExternalServiceUrls().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testExternalServiceUrlsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	externalServiceURLOne := &ExternalServiceURL{}
	externalServiceURLTwo := &ExternalServiceURL{}
	if err = randomize.Struct(seed, externalServiceURLOne, externalServiceURLDBTypes, false, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}
	if err = randomize.Struct(seed, externalServiceURLTwo, externalServiceURLDBTypes, false, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = externalServiceURLOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = externalServiceURLTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ExternalServiceUrls().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testExternalServiceUrlsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	externalServiceURLOne := &ExternalServiceURL{}
	externalServiceURLTwo := &ExternalServiceURL{}
	if err = randomize.Struct(seed, externalServiceURLOne, externalServiceURLDBTypes, false, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}
	if err = randomize.Struct(seed, externalServiceURLTwo, externalServiceURLDBTypes, false, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = externalServiceURLOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = externalServiceURLTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func externalServiceURLBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func externalServiceURLAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ExternalServiceURL) error {
	*o = ExternalServiceURL{}
	return nil
}

func testExternalServiceUrlsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ExternalServiceURL{}
	o := &ExternalServiceURL{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL object: %s", err)
	}

	AddExternalServiceURLHook(boil.BeforeInsertHook, externalServiceURLBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	externalServiceURLBeforeInsertHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.AfterInsertHook, externalServiceURLAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	externalServiceURLAfterInsertHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.AfterSelectHook, externalServiceURLAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	externalServiceURLAfterSelectHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.BeforeUpdateHook, externalServiceURLBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	externalServiceURLBeforeUpdateHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.AfterUpdateHook, externalServiceURLAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	externalServiceURLAfterUpdateHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.BeforeDeleteHook, externalServiceURLBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	externalServiceURLBeforeDeleteHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.AfterDeleteHook, externalServiceURLAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	externalServiceURLAfterDeleteHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.BeforeUpsertHook, externalServiceURLBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	externalServiceURLBeforeUpsertHooks = []ExternalServiceURLHook{}

	AddExternalServiceURLHook(boil.AfterUpsertHook, externalServiceURLAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	externalServiceURLAfterUpsertHooks = []ExternalServiceURLHook{}
}

func testExternalServiceUrlsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testExternalServiceUrlsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(externalServiceURLColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testExternalServiceURLToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ExternalServiceURL
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, externalServiceURLDBTypes, false, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ExternalServiceURLSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*ExternalServiceURL)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testExternalServiceURLToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ExternalServiceURL
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, externalServiceURLDBTypes, false, strmangle.SetComplement(externalServiceURLPrimaryKeyColumns, externalServiceURLColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ExternalServiceUrls[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testExternalServiceUrlsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testExternalServiceUrlsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ExternalServiceURLSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testExternalServiceUrlsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ExternalServiceUrls().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	externalServiceURLDBTypes = map[string]string{`ID`: `varchar`, `URL`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`, `UserID`: `varchar`, `ServiceType`: `int`}
	_                         = bytes.MinRead
)

func testExternalServiceUrlsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(externalServiceURLPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(externalServiceURLAllColumns) == len(externalServiceURLPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testExternalServiceUrlsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(externalServiceURLAllColumns) == len(externalServiceURLPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ExternalServiceURL{}
	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, externalServiceURLDBTypes, true, externalServiceURLPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(externalServiceURLAllColumns, externalServiceURLPrimaryKeyColumns) {
		fields = externalServiceURLAllColumns
	} else {
		fields = strmangle.SetComplement(
			externalServiceURLAllColumns,
			externalServiceURLPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ExternalServiceURLSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testExternalServiceUrlsUpsert(t *testing.T) {
	t.Parallel()

	if len(externalServiceURLAllColumns) == len(externalServiceURLPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLExternalServiceURLUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ExternalServiceURL{}
	if err = randomize.Struct(seed, &o, externalServiceURLDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ExternalServiceURL: %s", err)
	}

	count, err := ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, externalServiceURLDBTypes, false, externalServiceURLPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ExternalServiceURL struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ExternalServiceURL: %s", err)
	}

	count, err = ExternalServiceUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
