// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BioImages", testBioImagesUpsert)

	t.Run("Certifications", testCertificationsUpsert)

	t.Run("ExternalServiceUrls", testExternalServiceUrlsUpsert)

	t.Run("Skills", testSkillsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("WorkHavingTags", testWorkHavingTagsUpsert)

	t.Run("WorkImages", testWorkImagesUpsert)

	t.Run("WorkTags", testWorkTagsUpsert)

	t.Run("WorkUrls", testWorkUrlsUpsert)

	t.Run("Works", testWorksUpsert)
}
