// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkImages(t *testing.T) {
	t.Parallel()

	query := WorkImages()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkImagesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkImagesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := WorkImages().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkImagesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkImageSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkImagesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkImageExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if WorkImage exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkImageExists to return true, but got false.")
	}
}

func testWorkImagesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workImageFound, err := FindWorkImage(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workImageFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkImagesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = WorkImages().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkImagesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := WorkImages().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkImagesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workImageOne := &WorkImage{}
	workImageTwo := &WorkImage{}
	if err = randomize.Struct(seed, workImageOne, workImageDBTypes, false, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}
	if err = randomize.Struct(seed, workImageTwo, workImageDBTypes, false, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workImageOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workImageTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkImages().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkImagesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workImageOne := &WorkImage{}
	workImageTwo := &WorkImage{}
	if err = randomize.Struct(seed, workImageOne, workImageDBTypes, false, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}
	if err = randomize.Struct(seed, workImageTwo, workImageDBTypes, false, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workImageOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workImageTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workImageBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func workImageAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkImage) error {
	*o = WorkImage{}
	return nil
}

func testWorkImagesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &WorkImage{}
	o := &WorkImage{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workImageDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkImage object: %s", err)
	}

	AddWorkImageHook(boil.BeforeInsertHook, workImageBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workImageBeforeInsertHooks = []WorkImageHook{}

	AddWorkImageHook(boil.AfterInsertHook, workImageAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workImageAfterInsertHooks = []WorkImageHook{}

	AddWorkImageHook(boil.AfterSelectHook, workImageAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workImageAfterSelectHooks = []WorkImageHook{}

	AddWorkImageHook(boil.BeforeUpdateHook, workImageBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workImageBeforeUpdateHooks = []WorkImageHook{}

	AddWorkImageHook(boil.AfterUpdateHook, workImageAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workImageAfterUpdateHooks = []WorkImageHook{}

	AddWorkImageHook(boil.BeforeDeleteHook, workImageBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workImageBeforeDeleteHooks = []WorkImageHook{}

	AddWorkImageHook(boil.AfterDeleteHook, workImageAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workImageAfterDeleteHooks = []WorkImageHook{}

	AddWorkImageHook(boil.BeforeUpsertHook, workImageBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workImageBeforeUpsertHooks = []WorkImageHook{}

	AddWorkImageHook(boil.AfterUpsertHook, workImageAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workImageAfterUpsertHooks = []WorkImageHook{}
}

func testWorkImagesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkImagesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(workImageColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkImageToOneWorkUsingWork(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local WorkImage
	var foreign Work

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, workImageDBTypes, false, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, workDBTypes, false, workColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Work struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.WorkID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Work().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddWorkHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Work) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WorkImageSlice{&local}
	if err = local.L.LoadWork(ctx, tx, false, (*[]*WorkImage)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Work == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Work = nil
	if err = local.L.LoadWork(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Work == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWorkImageToOneSetOpWorkUsingWork(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkImage
	var b, c Work

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workImageDBTypes, false, strmangle.SetComplement(workImagePrimaryKeyColumns, workImageColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, workDBTypes, false, strmangle.SetComplement(workPrimaryKeyColumns, workColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workDBTypes, false, strmangle.SetComplement(workPrimaryKeyColumns, workColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Work{&b, &c} {
		err = a.SetWork(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Work != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WorkImages[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WorkID != x.ID {
			t.Error("foreign key was wrong value", a.WorkID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WorkID))
		reflect.Indirect(reflect.ValueOf(&a.WorkID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WorkID != x.ID {
			t.Error("foreign key was wrong value", a.WorkID, x.ID)
		}
	}
}

func testWorkImagesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkImagesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkImageSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkImagesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkImages().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workImageDBTypes = map[string]string{`ID`: `int`, `FileName`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`, `WorkID`: `varchar`}
	_                = bytes.MinRead
)

func testWorkImagesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workImagePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workImageAllColumns) == len(workImagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkImagesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workImageAllColumns) == len(workImagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkImage{}
	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImageColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workImageDBTypes, true, workImagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workImageAllColumns, workImagePrimaryKeyColumns) {
		fields = workImageAllColumns
	} else {
		fields = strmangle.SetComplement(
			workImageAllColumns,
			workImagePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkImageSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkImagesUpsert(t *testing.T) {
	t.Parallel()

	if len(workImageAllColumns) == len(workImagePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLWorkImageUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := WorkImage{}
	if err = randomize.Struct(seed, &o, workImageDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkImage: %s", err)
	}

	count, err := WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workImageDBTypes, false, workImagePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkImage struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkImage: %s", err)
	}

	count, err = WorkImages().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
