// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// WorkImage is an object representing the database table.
type WorkImage struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	FileName  string    `boil:"file_name" json:"file_name" toml:"file_name" yaml:"file_name"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	WorkID    string    `boil:"work_id" json:"work_id" toml:"work_id" yaml:"work_id"`

	R *workImageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workImageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkImageColumns = struct {
	ID        string
	FileName  string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	WorkID    string
}{
	ID:        "id",
	FileName:  "file_name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	WorkID:    "work_id",
}

var WorkImageTableColumns = struct {
	ID        string
	FileName  string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	WorkID    string
}{
	ID:        "work_images.id",
	FileName:  "work_images.file_name",
	CreatedAt: "work_images.created_at",
	UpdatedAt: "work_images.updated_at",
	DeletedAt: "work_images.deleted_at",
	WorkID:    "work_images.work_id",
}

// Generated where

var WorkImageWhere = struct {
	ID        whereHelperint
	FileName  whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
	DeletedAt whereHelpernull_Time
	WorkID    whereHelperstring
}{
	ID:        whereHelperint{field: "`work_images`.`id`"},
	FileName:  whereHelperstring{field: "`work_images`.`file_name`"},
	CreatedAt: whereHelpertime_Time{field: "`work_images`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`work_images`.`updated_at`"},
	DeletedAt: whereHelpernull_Time{field: "`work_images`.`deleted_at`"},
	WorkID:    whereHelperstring{field: "`work_images`.`work_id`"},
}

// WorkImageRels is where relationship names are stored.
var WorkImageRels = struct {
	Work string
}{
	Work: "Work",
}

// workImageR is where relationships are stored.
type workImageR struct {
	Work *Work `boil:"Work" json:"Work" toml:"Work" yaml:"Work"`
}

// NewStruct creates a new relationship struct
func (*workImageR) NewStruct() *workImageR {
	return &workImageR{}
}

func (r *workImageR) GetWork() *Work {
	if r == nil {
		return nil
	}
	return r.Work
}

// workImageL is where Load methods for each relationship are stored.
type workImageL struct{}

var (
	workImageAllColumns            = []string{"id", "file_name", "created_at", "updated_at", "deleted_at", "work_id"}
	workImageColumnsWithoutDefault = []string{"file_name", "deleted_at", "work_id"}
	workImageColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	workImagePrimaryKeyColumns     = []string{"id"}
	workImageGeneratedColumns      = []string{}
)

type (
	// WorkImageSlice is an alias for a slice of pointers to WorkImage.
	// This should almost always be used instead of []WorkImage.
	WorkImageSlice []*WorkImage
	// WorkImageHook is the signature for custom WorkImage hook methods
	WorkImageHook func(context.Context, boil.ContextExecutor, *WorkImage) error

	workImageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workImageType                 = reflect.TypeOf(&WorkImage{})
	workImageMapping              = queries.MakeStructMapping(workImageType)
	workImagePrimaryKeyMapping, _ = queries.BindMapping(workImageType, workImageMapping, workImagePrimaryKeyColumns)
	workImageInsertCacheMut       sync.RWMutex
	workImageInsertCache          = make(map[string]insertCache)
	workImageUpdateCacheMut       sync.RWMutex
	workImageUpdateCache          = make(map[string]updateCache)
	workImageUpsertCacheMut       sync.RWMutex
	workImageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workImageAfterSelectMu sync.Mutex
var workImageAfterSelectHooks []WorkImageHook

var workImageBeforeInsertMu sync.Mutex
var workImageBeforeInsertHooks []WorkImageHook
var workImageAfterInsertMu sync.Mutex
var workImageAfterInsertHooks []WorkImageHook

var workImageBeforeUpdateMu sync.Mutex
var workImageBeforeUpdateHooks []WorkImageHook
var workImageAfterUpdateMu sync.Mutex
var workImageAfterUpdateHooks []WorkImageHook

var workImageBeforeDeleteMu sync.Mutex
var workImageBeforeDeleteHooks []WorkImageHook
var workImageAfterDeleteMu sync.Mutex
var workImageAfterDeleteHooks []WorkImageHook

var workImageBeforeUpsertMu sync.Mutex
var workImageBeforeUpsertHooks []WorkImageHook
var workImageAfterUpsertMu sync.Mutex
var workImageAfterUpsertHooks []WorkImageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkImage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkImage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkImage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkImage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkImage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkImage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkImage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkImage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkImage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workImageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkImageHook registers your hook function for all future operations.
func AddWorkImageHook(hookPoint boil.HookPoint, workImageHook WorkImageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workImageAfterSelectMu.Lock()
		workImageAfterSelectHooks = append(workImageAfterSelectHooks, workImageHook)
		workImageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workImageBeforeInsertMu.Lock()
		workImageBeforeInsertHooks = append(workImageBeforeInsertHooks, workImageHook)
		workImageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workImageAfterInsertMu.Lock()
		workImageAfterInsertHooks = append(workImageAfterInsertHooks, workImageHook)
		workImageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workImageBeforeUpdateMu.Lock()
		workImageBeforeUpdateHooks = append(workImageBeforeUpdateHooks, workImageHook)
		workImageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workImageAfterUpdateMu.Lock()
		workImageAfterUpdateHooks = append(workImageAfterUpdateHooks, workImageHook)
		workImageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workImageBeforeDeleteMu.Lock()
		workImageBeforeDeleteHooks = append(workImageBeforeDeleteHooks, workImageHook)
		workImageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workImageAfterDeleteMu.Lock()
		workImageAfterDeleteHooks = append(workImageAfterDeleteHooks, workImageHook)
		workImageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workImageBeforeUpsertMu.Lock()
		workImageBeforeUpsertHooks = append(workImageBeforeUpsertHooks, workImageHook)
		workImageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workImageAfterUpsertMu.Lock()
		workImageAfterUpsertHooks = append(workImageAfterUpsertHooks, workImageHook)
		workImageAfterUpsertMu.Unlock()
	}
}

// One returns a single workImage record from the query.
func (q workImageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkImage, error) {
	o := &WorkImage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for work_images")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkImage records from the query.
func (q workImageQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkImageSlice, error) {
	var o []*WorkImage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WorkImage slice")
	}

	if len(workImageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkImage records in the query.
func (q workImageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count work_images rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workImageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if work_images exists")
	}

	return count > 0, nil
}

// Work pointed to by the foreign key.
func (o *WorkImage) Work(mods ...qm.QueryMod) workQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.WorkID),
	}

	queryMods = append(queryMods, mods...)

	return Works(queryMods...)
}

// LoadWork allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workImageL) LoadWork(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkImage interface{}, mods queries.Applicator) error {
	var slice []*WorkImage
	var object *WorkImage

	if singular {
		var ok bool
		object, ok = maybeWorkImage.(*WorkImage)
		if !ok {
			object = new(WorkImage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkImage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkImage))
			}
		}
	} else {
		s, ok := maybeWorkImage.(*[]*WorkImage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkImage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkImage))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workImageR{}
		}
		args[object.WorkID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workImageR{}
			}

			args[obj.WorkID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`works`),
		qm.WhereIn(`works.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Work")
	}

	var resultSlice []*Work
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Work")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for works")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for works")
	}

	if len(workAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Work = foreign
		if foreign.R == nil {
			foreign.R = &workR{}
		}
		foreign.R.WorkImages = append(foreign.R.WorkImages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkID == foreign.ID {
				local.R.Work = foreign
				if foreign.R == nil {
					foreign.R = &workR{}
				}
				foreign.R.WorkImages = append(foreign.R.WorkImages, local)
				break
			}
		}
	}

	return nil
}

// SetWork of the workImage to the related item.
// Sets o.R.Work to related.
// Adds o to related.R.WorkImages.
func (o *WorkImage) SetWork(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Work) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `work_images` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"work_id"}),
		strmangle.WhereClause("`", "`", 0, workImagePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkID = related.ID
	if o.R == nil {
		o.R = &workImageR{
			Work: related,
		}
	} else {
		o.R.Work = related
	}

	if related.R == nil {
		related.R = &workR{
			WorkImages: WorkImageSlice{o},
		}
	} else {
		related.R.WorkImages = append(related.R.WorkImages, o)
	}

	return nil
}

// WorkImages retrieves all the records using an executor.
func WorkImages(mods ...qm.QueryMod) workImageQuery {
	mods = append(mods, qm.From("`work_images`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`work_images`.*"})
	}

	return workImageQuery{q}
}

// FindWorkImage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkImage(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*WorkImage, error) {
	workImageObj := &WorkImage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `work_images` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workImageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from work_images")
	}

	if err = workImageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workImageObj, err
	}

	return workImageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkImage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no work_images provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workImageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workImageInsertCacheMut.RLock()
	cache, cached := workImageInsertCache[key]
	workImageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workImageAllColumns,
			workImageColumnsWithDefault,
			workImageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workImageType, workImageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workImageType, workImageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `work_images` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `work_images` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `work_images` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, workImagePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into work_images")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == workImageMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for work_images")
	}

CacheNoHooks:
	if !cached {
		workImageInsertCacheMut.Lock()
		workImageInsertCache[key] = cache
		workImageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkImage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkImage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workImageUpdateCacheMut.RLock()
	cache, cached := workImageUpdateCache[key]
	workImageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workImageAllColumns,
			workImagePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update work_images, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `work_images` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, workImagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workImageType, workImageMapping, append(wl, workImagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update work_images row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for work_images")
	}

	if !cached {
		workImageUpdateCacheMut.Lock()
		workImageUpdateCache[key] = cache
		workImageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workImageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for work_images")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for work_images")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkImageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workImagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `work_images` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workImagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in workImage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all workImage")
	}
	return rowsAff, nil
}

var mySQLWorkImageUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkImage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no work_images provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workImageColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLWorkImageUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workImageUpsertCacheMut.RLock()
	cache, cached := workImageUpsertCache[key]
	workImageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workImageAllColumns,
			workImageColumnsWithDefault,
			workImageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workImageAllColumns,
			workImagePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert work_images, could not build update column list")
		}

		ret := strmangle.SetComplement(workImageAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`work_images`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `work_images` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(workImageType, workImageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workImageType, workImageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for work_images")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == workImageMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(workImageType, workImageMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for work_images")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for work_images")
	}

CacheNoHooks:
	if !cached {
		workImageUpsertCacheMut.Lock()
		workImageUpsertCache[key] = cache
		workImageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkImage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkImage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WorkImage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workImagePrimaryKeyMapping)
	sql := "DELETE FROM `work_images` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from work_images")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for work_images")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workImageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workImageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from work_images")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for work_images")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkImageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workImageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workImagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `work_images` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workImagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workImage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for work_images")
	}

	if len(workImageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkImage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkImage(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkImageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkImageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workImagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `work_images`.* FROM `work_images` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workImagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkImageSlice")
	}

	*o = slice

	return nil
}

// WorkImageExists checks if the WorkImage row exists.
func WorkImageExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `work_images` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if work_images exists")
	}

	return exists, nil
}

// Exists checks if the WorkImage row exists.
func (o *WorkImage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkImageExists(ctx, exec, o.ID)
}
