// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkUrls(t *testing.T) {
	t.Parallel()

	query := WorkUrls()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkUrlsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkUrlsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := WorkUrls().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkUrlsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkURLSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkUrlsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkURLExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if WorkURL exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkURLExists to return true, but got false.")
	}
}

func testWorkUrlsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workURLFound, err := FindWorkURL(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workURLFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkUrlsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = WorkUrls().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkUrlsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := WorkUrls().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkUrlsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workURLOne := &WorkURL{}
	workURLTwo := &WorkURL{}
	if err = randomize.Struct(seed, workURLOne, workURLDBTypes, false, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}
	if err = randomize.Struct(seed, workURLTwo, workURLDBTypes, false, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workURLOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workURLTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkUrls().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkUrlsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workURLOne := &WorkURL{}
	workURLTwo := &WorkURL{}
	if err = randomize.Struct(seed, workURLOne, workURLDBTypes, false, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}
	if err = randomize.Struct(seed, workURLTwo, workURLDBTypes, false, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workURLOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workURLTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workURLBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func workURLAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkURL) error {
	*o = WorkURL{}
	return nil
}

func testWorkUrlsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &WorkURL{}
	o := &WorkURL{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workURLDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkURL object: %s", err)
	}

	AddWorkURLHook(boil.BeforeInsertHook, workURLBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workURLBeforeInsertHooks = []WorkURLHook{}

	AddWorkURLHook(boil.AfterInsertHook, workURLAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workURLAfterInsertHooks = []WorkURLHook{}

	AddWorkURLHook(boil.AfterSelectHook, workURLAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workURLAfterSelectHooks = []WorkURLHook{}

	AddWorkURLHook(boil.BeforeUpdateHook, workURLBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workURLBeforeUpdateHooks = []WorkURLHook{}

	AddWorkURLHook(boil.AfterUpdateHook, workURLAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workURLAfterUpdateHooks = []WorkURLHook{}

	AddWorkURLHook(boil.BeforeDeleteHook, workURLBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workURLBeforeDeleteHooks = []WorkURLHook{}

	AddWorkURLHook(boil.AfterDeleteHook, workURLAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workURLAfterDeleteHooks = []WorkURLHook{}

	AddWorkURLHook(boil.BeforeUpsertHook, workURLBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workURLBeforeUpsertHooks = []WorkURLHook{}

	AddWorkURLHook(boil.AfterUpsertHook, workURLAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workURLAfterUpsertHooks = []WorkURLHook{}
}

func testWorkUrlsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkUrlsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(workURLColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkURLToOneWorkUsingWork(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local WorkURL
	var foreign Work

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, workURLDBTypes, false, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, workDBTypes, false, workColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Work struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.WorkID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Work().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddWorkHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Work) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WorkURLSlice{&local}
	if err = local.L.LoadWork(ctx, tx, false, (*[]*WorkURL)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Work == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Work = nil
	if err = local.L.LoadWork(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Work == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWorkURLToOneSetOpWorkUsingWork(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkURL
	var b, c Work

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workURLDBTypes, false, strmangle.SetComplement(workURLPrimaryKeyColumns, workURLColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, workDBTypes, false, strmangle.SetComplement(workPrimaryKeyColumns, workColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workDBTypes, false, strmangle.SetComplement(workPrimaryKeyColumns, workColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Work{&b, &c} {
		err = a.SetWork(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Work != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WorkUrls[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WorkID != x.ID {
			t.Error("foreign key was wrong value", a.WorkID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WorkID))
		reflect.Indirect(reflect.ValueOf(&a.WorkID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WorkID != x.ID {
			t.Error("foreign key was wrong value", a.WorkID, x.ID)
		}
	}
}

func testWorkUrlsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkUrlsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkURLSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkUrlsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkUrls().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workURLDBTypes = map[string]string{`ID`: `varchar`, `URL`: `varchar`, `Title`: `varchar`, `WorkID`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`}
	_              = bytes.MinRead
)

func testWorkUrlsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workURLPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workURLAllColumns) == len(workURLPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkUrlsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workURLAllColumns) == len(workURLPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkURL{}
	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workURLDBTypes, true, workURLPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workURLAllColumns, workURLPrimaryKeyColumns) {
		fields = workURLAllColumns
	} else {
		fields = strmangle.SetComplement(
			workURLAllColumns,
			workURLPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkURLSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkUrlsUpsert(t *testing.T) {
	t.Parallel()

	if len(workURLAllColumns) == len(workURLPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLWorkURLUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := WorkURL{}
	if err = randomize.Struct(seed, &o, workURLDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkURL: %s", err)
	}

	count, err := WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workURLDBTypes, false, workURLPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkURL struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkURL: %s", err)
	}

	count, err = WorkUrls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
