// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkTags(t *testing.T) {
	t.Parallel()

	query := WorkTags()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkTagsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkTagsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := WorkTags().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkTagsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkTagSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkTagsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkTagExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if WorkTag exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkTagExists to return true, but got false.")
	}
}

func testWorkTagsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workTagFound, err := FindWorkTag(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workTagFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkTagsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = WorkTags().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkTagsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := WorkTags().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkTagsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workTagOne := &WorkTag{}
	workTagTwo := &WorkTag{}
	if err = randomize.Struct(seed, workTagOne, workTagDBTypes, false, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}
	if err = randomize.Struct(seed, workTagTwo, workTagDBTypes, false, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workTagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workTagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkTags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkTagsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workTagOne := &WorkTag{}
	workTagTwo := &WorkTag{}
	if err = randomize.Struct(seed, workTagOne, workTagDBTypes, false, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}
	if err = randomize.Struct(seed, workTagTwo, workTagDBTypes, false, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workTagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workTagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workTagBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func workTagAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
	*o = WorkTag{}
	return nil
}

func testWorkTagsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &WorkTag{}
	o := &WorkTag{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workTagDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkTag object: %s", err)
	}

	AddWorkTagHook(boil.BeforeInsertHook, workTagBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workTagBeforeInsertHooks = []WorkTagHook{}

	AddWorkTagHook(boil.AfterInsertHook, workTagAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workTagAfterInsertHooks = []WorkTagHook{}

	AddWorkTagHook(boil.AfterSelectHook, workTagAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workTagAfterSelectHooks = []WorkTagHook{}

	AddWorkTagHook(boil.BeforeUpdateHook, workTagBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workTagBeforeUpdateHooks = []WorkTagHook{}

	AddWorkTagHook(boil.AfterUpdateHook, workTagAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workTagAfterUpdateHooks = []WorkTagHook{}

	AddWorkTagHook(boil.BeforeDeleteHook, workTagBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workTagBeforeDeleteHooks = []WorkTagHook{}

	AddWorkTagHook(boil.AfterDeleteHook, workTagAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workTagAfterDeleteHooks = []WorkTagHook{}

	AddWorkTagHook(boil.BeforeUpsertHook, workTagBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workTagBeforeUpsertHooks = []WorkTagHook{}

	AddWorkTagHook(boil.AfterUpsertHook, workTagAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workTagAfterUpsertHooks = []WorkTagHook{}
}

func testWorkTagsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkTagsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(workTagColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkTagToManyWorkHavingTags(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkTag
	var b, c WorkHavingTag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.WorkTagID = a.ID
	c.WorkTagID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.WorkHavingTags().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.WorkTagID == b.WorkTagID {
			bFound = true
		}
		if v.WorkTagID == c.WorkTagID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WorkTagSlice{&a}
	if err = a.L.LoadWorkHavingTags(ctx, tx, false, (*[]*WorkTag)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WorkHavingTags); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.WorkHavingTags = nil
	if err = a.L.LoadWorkHavingTags(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WorkHavingTags); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWorkTagToManyAddOpWorkHavingTags(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkTag
	var b, c, d, e WorkHavingTag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workTagDBTypes, false, strmangle.SetComplement(workTagPrimaryKeyColumns, workTagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WorkHavingTag{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, workHavingTagDBTypes, false, strmangle.SetComplement(workHavingTagPrimaryKeyColumns, workHavingTagColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*WorkHavingTag{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWorkHavingTags(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.WorkTagID {
			t.Error("foreign key was wrong value", a.ID, first.WorkTagID)
		}
		if a.ID != second.WorkTagID {
			t.Error("foreign key was wrong value", a.ID, second.WorkTagID)
		}

		if first.R.WorkTag != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.WorkTag != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.WorkHavingTags[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.WorkHavingTags[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.WorkHavingTags().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testWorkTagsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkTagsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkTagSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkTagsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkTags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workTagDBTypes = map[string]string{`ID`: `varchar`, `Name`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`}
	_              = bytes.MinRead
)

func testWorkTagsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workTagPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workTagAllColumns) == len(workTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkTagsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workTagAllColumns) == len(workTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkTag{}
	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workTagDBTypes, true, workTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workTagAllColumns, workTagPrimaryKeyColumns) {
		fields = workTagAllColumns
	} else {
		fields = strmangle.SetComplement(
			workTagAllColumns,
			workTagPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkTagSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkTagsUpsert(t *testing.T) {
	t.Parallel()

	if len(workTagAllColumns) == len(workTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLWorkTagUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := WorkTag{}
	if err = randomize.Struct(seed, &o, workTagDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkTag: %s", err)
	}

	count, err := WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workTagDBTypes, false, workTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkTag: %s", err)
	}

	count, err = WorkTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
