// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// WorkHavingTag is an object representing the database table.
type WorkHavingTag struct {
	ID        uint64    `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkID    string    `boil:"work_id" json:"work_id" toml:"work_id" yaml:"work_id"`
	WorkTagID string    `boil:"work_tag_id" json:"work_tag_id" toml:"work_tag_id" yaml:"work_tag_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *workHavingTagR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workHavingTagL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkHavingTagColumns = struct {
	ID        string
	WorkID    string
	WorkTagID string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	ID:        "id",
	WorkID:    "work_id",
	WorkTagID: "work_tag_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

var WorkHavingTagTableColumns = struct {
	ID        string
	WorkID    string
	WorkTagID string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	ID:        "work_having_tags.id",
	WorkID:    "work_having_tags.work_id",
	WorkTagID: "work_having_tags.work_tag_id",
	CreatedAt: "work_having_tags.created_at",
	UpdatedAt: "work_having_tags.updated_at",
	DeletedAt: "work_having_tags.deleted_at",
}

// Generated where

var WorkHavingTagWhere = struct {
	ID        whereHelperstring
	WorkID    whereHelperstring
	WorkTagID whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
	DeletedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "`work_having_tags`.`id`"},
	WorkID:    whereHelperstring{field: "`work_having_tags`.`work_id`"},
	WorkTagID: whereHelperstring{field: "`work_having_tags`.`work_tag_id`"},
	CreatedAt: whereHelpertime_Time{field: "`work_having_tags`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`work_having_tags`.`updated_at`"},
	DeletedAt: whereHelpernull_Time{field: "`work_having_tags`.`deleted_at`"},
}

// WorkHavingTagRels is where relationship names are stored.
var WorkHavingTagRels = struct {
	Work    string
	WorkTag string
}{
	Work:    "Work",
	WorkTag: "WorkTag",
}

// workHavingTagR is where relationships are stored.
type workHavingTagR struct {
	Work    *Work    `boil:"Work" json:"Work" toml:"Work" yaml:"Work"`
	WorkTag *WorkTag `boil:"WorkTag" json:"WorkTag" toml:"WorkTag" yaml:"WorkTag"`
}

// NewStruct creates a new relationship struct
func (*workHavingTagR) NewStruct() *workHavingTagR {
	return &workHavingTagR{}
}

func (r *workHavingTagR) GetWork() *Work {
	if r == nil {
		return nil
	}
	return r.Work
}

func (r *workHavingTagR) GetWorkTag() *WorkTag {
	if r == nil {
		return nil
	}
	return r.WorkTag
}

// workHavingTagL is where Load methods for each relationship are stored.
type workHavingTagL struct{}

var (
	workHavingTagAllColumns            = []string{"id", "work_id", "work_tag_id", "created_at", "updated_at", "deleted_at"}
	workHavingTagColumnsWithoutDefault = []string{"id", "work_id", "work_tag_id", "deleted_at"}
	workHavingTagColumnsWithDefault    = []string{"created_at", "updated_at"}
	workHavingTagPrimaryKeyColumns     = []string{"id"}
	workHavingTagGeneratedColumns      = []string{}
)

type (
	// WorkHavingTagSlice is an alias for a slice of pointers to WorkHavingTag.
	// This should almost always be used instead of []WorkHavingTag.
	WorkHavingTagSlice []*WorkHavingTag
	// WorkHavingTagHook is the signature for custom WorkHavingTag hook methods
	WorkHavingTagHook func(context.Context, boil.ContextExecutor, *WorkHavingTag) error

	workHavingTagQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workHavingTagType                 = reflect.TypeOf(&WorkHavingTag{})
	workHavingTagMapping              = queries.MakeStructMapping(workHavingTagType)
	workHavingTagPrimaryKeyMapping, _ = queries.BindMapping(workHavingTagType, workHavingTagMapping, workHavingTagPrimaryKeyColumns)
	workHavingTagInsertCacheMut       sync.RWMutex
	workHavingTagInsertCache          = make(map[string]insertCache)
	workHavingTagUpdateCacheMut       sync.RWMutex
	workHavingTagUpdateCache          = make(map[string]updateCache)
	workHavingTagUpsertCacheMut       sync.RWMutex
	workHavingTagUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workHavingTagAfterSelectMu sync.Mutex
var workHavingTagAfterSelectHooks []WorkHavingTagHook

var workHavingTagBeforeInsertMu sync.Mutex
var workHavingTagBeforeInsertHooks []WorkHavingTagHook
var workHavingTagAfterInsertMu sync.Mutex
var workHavingTagAfterInsertHooks []WorkHavingTagHook

var workHavingTagBeforeUpdateMu sync.Mutex
var workHavingTagBeforeUpdateHooks []WorkHavingTagHook
var workHavingTagAfterUpdateMu sync.Mutex
var workHavingTagAfterUpdateHooks []WorkHavingTagHook

var workHavingTagBeforeDeleteMu sync.Mutex
var workHavingTagBeforeDeleteHooks []WorkHavingTagHook
var workHavingTagAfterDeleteMu sync.Mutex
var workHavingTagAfterDeleteHooks []WorkHavingTagHook

var workHavingTagBeforeUpsertMu sync.Mutex
var workHavingTagBeforeUpsertHooks []WorkHavingTagHook
var workHavingTagAfterUpsertMu sync.Mutex
var workHavingTagAfterUpsertHooks []WorkHavingTagHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkHavingTag) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkHavingTag) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkHavingTag) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkHavingTag) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkHavingTag) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkHavingTag) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkHavingTag) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkHavingTag) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkHavingTag) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workHavingTagAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkHavingTagHook registers your hook function for all future operations.
func AddWorkHavingTagHook(hookPoint boil.HookPoint, workHavingTagHook WorkHavingTagHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workHavingTagAfterSelectMu.Lock()
		workHavingTagAfterSelectHooks = append(workHavingTagAfterSelectHooks, workHavingTagHook)
		workHavingTagAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workHavingTagBeforeInsertMu.Lock()
		workHavingTagBeforeInsertHooks = append(workHavingTagBeforeInsertHooks, workHavingTagHook)
		workHavingTagBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workHavingTagAfterInsertMu.Lock()
		workHavingTagAfterInsertHooks = append(workHavingTagAfterInsertHooks, workHavingTagHook)
		workHavingTagAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workHavingTagBeforeUpdateMu.Lock()
		workHavingTagBeforeUpdateHooks = append(workHavingTagBeforeUpdateHooks, workHavingTagHook)
		workHavingTagBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workHavingTagAfterUpdateMu.Lock()
		workHavingTagAfterUpdateHooks = append(workHavingTagAfterUpdateHooks, workHavingTagHook)
		workHavingTagAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workHavingTagBeforeDeleteMu.Lock()
		workHavingTagBeforeDeleteHooks = append(workHavingTagBeforeDeleteHooks, workHavingTagHook)
		workHavingTagBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workHavingTagAfterDeleteMu.Lock()
		workHavingTagAfterDeleteHooks = append(workHavingTagAfterDeleteHooks, workHavingTagHook)
		workHavingTagAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workHavingTagBeforeUpsertMu.Lock()
		workHavingTagBeforeUpsertHooks = append(workHavingTagBeforeUpsertHooks, workHavingTagHook)
		workHavingTagBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workHavingTagAfterUpsertMu.Lock()
		workHavingTagAfterUpsertHooks = append(workHavingTagAfterUpsertHooks, workHavingTagHook)
		workHavingTagAfterUpsertMu.Unlock()
	}
}

// One returns a single workHavingTag record from the query.
func (q workHavingTagQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkHavingTag, error) {
	o := &WorkHavingTag{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for work_having_tags")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkHavingTag records from the query.
func (q workHavingTagQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkHavingTagSlice, error) {
	var o []*WorkHavingTag

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WorkHavingTag slice")
	}

	if len(workHavingTagAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkHavingTag records in the query.
func (q workHavingTagQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count work_having_tags rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workHavingTagQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if work_having_tags exists")
	}

	return count > 0, nil
}

// Work pointed to by the foreign key.
func (o *WorkHavingTag) Work(mods ...qm.QueryMod) workQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.WorkID),
	}

	queryMods = append(queryMods, mods...)

	return Works(queryMods...)
}

// WorkTag pointed to by the foreign key.
func (o *WorkHavingTag) WorkTag(mods ...qm.QueryMod) workTagQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.WorkTagID),
	}

	queryMods = append(queryMods, mods...)

	return WorkTags(queryMods...)
}

// LoadWork allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workHavingTagL) LoadWork(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkHavingTag interface{}, mods queries.Applicator) error {
	var slice []*WorkHavingTag
	var object *WorkHavingTag

	if singular {
		var ok bool
		object, ok = maybeWorkHavingTag.(*WorkHavingTag)
		if !ok {
			object = new(WorkHavingTag)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkHavingTag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkHavingTag))
			}
		}
	} else {
		s, ok := maybeWorkHavingTag.(*[]*WorkHavingTag)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkHavingTag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkHavingTag))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workHavingTagR{}
		}
		args[object.WorkID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workHavingTagR{}
			}

			args[obj.WorkID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`works`),
		qm.WhereIn(`works.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Work")
	}

	var resultSlice []*Work
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Work")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for works")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for works")
	}

	if len(workAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Work = foreign
		if foreign.R == nil {
			foreign.R = &workR{}
		}
		foreign.R.WorkHavingTags = append(foreign.R.WorkHavingTags, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkID == foreign.ID {
				local.R.Work = foreign
				if foreign.R == nil {
					foreign.R = &workR{}
				}
				foreign.R.WorkHavingTags = append(foreign.R.WorkHavingTags, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkTag allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workHavingTagL) LoadWorkTag(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkHavingTag interface{}, mods queries.Applicator) error {
	var slice []*WorkHavingTag
	var object *WorkHavingTag

	if singular {
		var ok bool
		object, ok = maybeWorkHavingTag.(*WorkHavingTag)
		if !ok {
			object = new(WorkHavingTag)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkHavingTag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkHavingTag))
			}
		}
	} else {
		s, ok := maybeWorkHavingTag.(*[]*WorkHavingTag)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkHavingTag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkHavingTag))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workHavingTagR{}
		}
		args[object.WorkTagID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workHavingTagR{}
			}

			args[obj.WorkTagID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`work_tags`),
		qm.WhereIn(`work_tags.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load WorkTag")
	}

	var resultSlice []*WorkTag
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice WorkTag")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for work_tags")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for work_tags")
	}

	if len(workTagAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.WorkTag = foreign
		if foreign.R == nil {
			foreign.R = &workTagR{}
		}
		foreign.R.WorkHavingTags = append(foreign.R.WorkHavingTags, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkTagID == foreign.ID {
				local.R.WorkTag = foreign
				if foreign.R == nil {
					foreign.R = &workTagR{}
				}
				foreign.R.WorkHavingTags = append(foreign.R.WorkHavingTags, local)
				break
			}
		}
	}

	return nil
}

// SetWork of the workHavingTag to the related item.
// Sets o.R.Work to related.
// Adds o to related.R.WorkHavingTags.
func (o *WorkHavingTag) SetWork(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Work) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `work_having_tags` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"work_id"}),
		strmangle.WhereClause("`", "`", 0, workHavingTagPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkID = related.ID
	if o.R == nil {
		o.R = &workHavingTagR{
			Work: related,
		}
	} else {
		o.R.Work = related
	}

	if related.R == nil {
		related.R = &workR{
			WorkHavingTags: WorkHavingTagSlice{o},
		}
	} else {
		related.R.WorkHavingTags = append(related.R.WorkHavingTags, o)
	}

	return nil
}

// SetWorkTag of the workHavingTag to the related item.
// Sets o.R.WorkTag to related.
// Adds o to related.R.WorkHavingTags.
func (o *WorkHavingTag) SetWorkTag(ctx context.Context, exec boil.ContextExecutor, insert bool, related *WorkTag) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `work_having_tags` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"work_tag_id"}),
		strmangle.WhereClause("`", "`", 0, workHavingTagPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkTagID = related.ID
	if o.R == nil {
		o.R = &workHavingTagR{
			WorkTag: related,
		}
	} else {
		o.R.WorkTag = related
	}

	if related.R == nil {
		related.R = &workTagR{
			WorkHavingTags: WorkHavingTagSlice{o},
		}
	} else {
		related.R.WorkHavingTags = append(related.R.WorkHavingTags, o)
	}

	return nil
}

// WorkHavingTags retrieves all the records using an executor.
func WorkHavingTags(mods ...qm.QueryMod) workHavingTagQuery {
	mods = append(mods, qm.From("`work_having_tags`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`work_having_tags`.*"})
	}

	return workHavingTagQuery{q}
}

// FindWorkHavingTag retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkHavingTag(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkHavingTag, error) {
	workHavingTagObj := &WorkHavingTag{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `work_having_tags` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workHavingTagObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from work_having_tags")
	}

	if err = workHavingTagObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workHavingTagObj, err
	}

	return workHavingTagObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkHavingTag) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no work_having_tags provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workHavingTagColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workHavingTagInsertCacheMut.RLock()
	cache, cached := workHavingTagInsertCache[key]
	workHavingTagInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workHavingTagAllColumns,
			workHavingTagColumnsWithDefault,
			workHavingTagColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workHavingTagType, workHavingTagMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workHavingTagType, workHavingTagMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `work_having_tags` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `work_having_tags` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `work_having_tags` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, workHavingTagPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into work_having_tags")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for work_having_tags")
	}

CacheNoHooks:
	if !cached {
		workHavingTagInsertCacheMut.Lock()
		workHavingTagInsertCache[key] = cache
		workHavingTagInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkHavingTag.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkHavingTag) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workHavingTagUpdateCacheMut.RLock()
	cache, cached := workHavingTagUpdateCache[key]
	workHavingTagUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workHavingTagAllColumns,
			workHavingTagPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update work_having_tags, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `work_having_tags` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, workHavingTagPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workHavingTagType, workHavingTagMapping, append(wl, workHavingTagPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update work_having_tags row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for work_having_tags")
	}

	if !cached {
		workHavingTagUpdateCacheMut.Lock()
		workHavingTagUpdateCache[key] = cache
		workHavingTagUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workHavingTagQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for work_having_tags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for work_having_tags")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkHavingTagSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workHavingTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `work_having_tags` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workHavingTagPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in workHavingTag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all workHavingTag")
	}
	return rowsAff, nil
}

var mySQLWorkHavingTagUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkHavingTag) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no work_having_tags provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workHavingTagColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLWorkHavingTagUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workHavingTagUpsertCacheMut.RLock()
	cache, cached := workHavingTagUpsertCache[key]
	workHavingTagUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workHavingTagAllColumns,
			workHavingTagColumnsWithDefault,
			workHavingTagColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workHavingTagAllColumns,
			workHavingTagPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert work_having_tags, could not build update column list")
		}

		ret := strmangle.SetComplement(workHavingTagAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`work_having_tags`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `work_having_tags` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(workHavingTagType, workHavingTagMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workHavingTagType, workHavingTagMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for work_having_tags")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(workHavingTagType, workHavingTagMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for work_having_tags")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for work_having_tags")
	}

CacheNoHooks:
	if !cached {
		workHavingTagUpsertCacheMut.Lock()
		workHavingTagUpsertCache[key] = cache
		workHavingTagUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkHavingTag record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkHavingTag) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WorkHavingTag provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workHavingTagPrimaryKeyMapping)
	sql := "DELETE FROM `work_having_tags` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from work_having_tags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for work_having_tags")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workHavingTagQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workHavingTagQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from work_having_tags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for work_having_tags")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkHavingTagSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workHavingTagBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workHavingTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `work_having_tags` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workHavingTagPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workHavingTag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for work_having_tags")
	}

	if len(workHavingTagAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkHavingTag) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkHavingTag(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkHavingTagSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkHavingTagSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workHavingTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `work_having_tags`.* FROM `work_having_tags` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workHavingTagPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkHavingTagSlice")
	}

	*o = slice

	return nil
}

// WorkHavingTagExists checks if the WorkHavingTag row exists.
func WorkHavingTagExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `work_having_tags` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if work_having_tags exists")
	}

	return exists, nil
}

// Exists checks if the WorkHavingTag row exists.
func (o *WorkHavingTag) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkHavingTagExists(ctx, exec, o.ID)
}
