// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWorkHavingTags(t *testing.T) {
	t.Parallel()

	query := WorkHavingTags()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWorkHavingTagsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkHavingTagsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := WorkHavingTags().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkHavingTagsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkHavingTagSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWorkHavingTagsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WorkHavingTagExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if WorkHavingTag exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WorkHavingTagExists to return true, but got false.")
	}
}

func testWorkHavingTagsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	workHavingTagFound, err := FindWorkHavingTag(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if workHavingTagFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWorkHavingTagsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = WorkHavingTags().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWorkHavingTagsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := WorkHavingTags().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWorkHavingTagsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	workHavingTagOne := &WorkHavingTag{}
	workHavingTagTwo := &WorkHavingTag{}
	if err = randomize.Struct(seed, workHavingTagOne, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}
	if err = randomize.Struct(seed, workHavingTagTwo, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workHavingTagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workHavingTagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkHavingTags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWorkHavingTagsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	workHavingTagOne := &WorkHavingTag{}
	workHavingTagTwo := &WorkHavingTag{}
	if err = randomize.Struct(seed, workHavingTagOne, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}
	if err = randomize.Struct(seed, workHavingTagTwo, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = workHavingTagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = workHavingTagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func workHavingTagBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func workHavingTagAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *WorkHavingTag) error {
	*o = WorkHavingTag{}
	return nil
}

func testWorkHavingTagsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &WorkHavingTag{}
	o := &WorkHavingTag{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag object: %s", err)
	}

	AddWorkHavingTagHook(boil.BeforeInsertHook, workHavingTagBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	workHavingTagBeforeInsertHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.AfterInsertHook, workHavingTagAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	workHavingTagAfterInsertHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.AfterSelectHook, workHavingTagAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	workHavingTagAfterSelectHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.BeforeUpdateHook, workHavingTagBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	workHavingTagBeforeUpdateHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.AfterUpdateHook, workHavingTagAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	workHavingTagAfterUpdateHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.BeforeDeleteHook, workHavingTagBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	workHavingTagBeforeDeleteHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.AfterDeleteHook, workHavingTagAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	workHavingTagAfterDeleteHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.BeforeUpsertHook, workHavingTagBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	workHavingTagBeforeUpsertHooks = []WorkHavingTagHook{}

	AddWorkHavingTagHook(boil.AfterUpsertHook, workHavingTagAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	workHavingTagAfterUpsertHooks = []WorkHavingTagHook{}
}

func testWorkHavingTagsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkHavingTagsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(workHavingTagColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWorkHavingTagToOneWorkUsingWork(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local WorkHavingTag
	var foreign Work

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, workDBTypes, false, workColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Work struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.WorkID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Work().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddWorkHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Work) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WorkHavingTagSlice{&local}
	if err = local.L.LoadWork(ctx, tx, false, (*[]*WorkHavingTag)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Work == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Work = nil
	if err = local.L.LoadWork(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Work == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWorkHavingTagToOneWorkTagUsingWorkTag(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local WorkHavingTag
	var foreign WorkTag

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, workHavingTagDBTypes, false, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, workTagDBTypes, false, workTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkTag struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.WorkTagID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.WorkTag().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddWorkTagHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *WorkTag) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WorkHavingTagSlice{&local}
	if err = local.L.LoadWorkTag(ctx, tx, false, (*[]*WorkHavingTag)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.WorkTag == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.WorkTag = nil
	if err = local.L.LoadWorkTag(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.WorkTag == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWorkHavingTagToOneSetOpWorkUsingWork(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkHavingTag
	var b, c Work

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workHavingTagDBTypes, false, strmangle.SetComplement(workHavingTagPrimaryKeyColumns, workHavingTagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, workDBTypes, false, strmangle.SetComplement(workPrimaryKeyColumns, workColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workDBTypes, false, strmangle.SetComplement(workPrimaryKeyColumns, workColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Work{&b, &c} {
		err = a.SetWork(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Work != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WorkHavingTags[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WorkID != x.ID {
			t.Error("foreign key was wrong value", a.WorkID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WorkID))
		reflect.Indirect(reflect.ValueOf(&a.WorkID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WorkID != x.ID {
			t.Error("foreign key was wrong value", a.WorkID, x.ID)
		}
	}
}
func testWorkHavingTagToOneSetOpWorkTagUsingWorkTag(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a WorkHavingTag
	var b, c WorkTag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, workHavingTagDBTypes, false, strmangle.SetComplement(workHavingTagPrimaryKeyColumns, workHavingTagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, workTagDBTypes, false, strmangle.SetComplement(workTagPrimaryKeyColumns, workTagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, workTagDBTypes, false, strmangle.SetComplement(workTagPrimaryKeyColumns, workTagColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*WorkTag{&b, &c} {
		err = a.SetWorkTag(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.WorkTag != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WorkHavingTags[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.WorkTagID != x.ID {
			t.Error("foreign key was wrong value", a.WorkTagID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WorkTagID))
		reflect.Indirect(reflect.ValueOf(&a.WorkTagID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.WorkTagID != x.ID {
			t.Error("foreign key was wrong value", a.WorkTagID, x.ID)
		}
	}
}

func testWorkHavingTagsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkHavingTagsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WorkHavingTagSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWorkHavingTagsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := WorkHavingTags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	workHavingTagDBTypes = map[string]string{`ID`: `varchar`, `WorkID`: `varchar`, `WorkTagID`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`}
	_                    = bytes.MinRead
)

func testWorkHavingTagsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(workHavingTagPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(workHavingTagAllColumns) == len(workHavingTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWorkHavingTagsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(workHavingTagAllColumns) == len(workHavingTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &WorkHavingTag{}
	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, workHavingTagDBTypes, true, workHavingTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(workHavingTagAllColumns, workHavingTagPrimaryKeyColumns) {
		fields = workHavingTagAllColumns
	} else {
		fields = strmangle.SetComplement(
			workHavingTagAllColumns,
			workHavingTagPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WorkHavingTagSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWorkHavingTagsUpsert(t *testing.T) {
	t.Parallel()

	if len(workHavingTagAllColumns) == len(workHavingTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLWorkHavingTagUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := WorkHavingTag{}
	if err = randomize.Struct(seed, &o, workHavingTagDBTypes, false); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkHavingTag: %s", err)
	}

	count, err := WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, workHavingTagDBTypes, false, workHavingTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize WorkHavingTag struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert WorkHavingTag: %s", err)
	}

	count, err = WorkHavingTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
