// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// WorkTag is an object representing the database table.
type WorkTag struct {
	ID        string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *workTagR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workTagL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkTagColumns = struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	ID:        "id",
	Name:      "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

var WorkTagTableColumns = struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
	DeletedAt string
}{
	ID:        "work_tags.id",
	Name:      "work_tags.name",
	CreatedAt: "work_tags.created_at",
	UpdatedAt: "work_tags.updated_at",
	DeletedAt: "work_tags.deleted_at",
}

// Generated where

var WorkTagWhere = struct {
	ID        whereHelperstring
	Name      whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
	DeletedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "`work_tags`.`id`"},
	Name:      whereHelperstring{field: "`work_tags`.`name`"},
	CreatedAt: whereHelpertime_Time{field: "`work_tags`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`work_tags`.`updated_at`"},
	DeletedAt: whereHelpernull_Time{field: "`work_tags`.`deleted_at`"},
}

// WorkTagRels is where relationship names are stored.
var WorkTagRels = struct {
	WorkHavingTags string
}{
	WorkHavingTags: "WorkHavingTags",
}

// workTagR is where relationships are stored.
type workTagR struct {
	WorkHavingTags WorkHavingTagSlice `boil:"WorkHavingTags" json:"WorkHavingTags" toml:"WorkHavingTags" yaml:"WorkHavingTags"`
}

// NewStruct creates a new relationship struct
func (*workTagR) NewStruct() *workTagR {
	return &workTagR{}
}

func (r *workTagR) GetWorkHavingTags() WorkHavingTagSlice {
	if r == nil {
		return nil
	}
	return r.WorkHavingTags
}

// workTagL is where Load methods for each relationship are stored.
type workTagL struct{}

var (
	workTagAllColumns            = []string{"id", "name", "created_at", "updated_at", "deleted_at"}
	workTagColumnsWithoutDefault = []string{"id", "name", "deleted_at"}
	workTagColumnsWithDefault    = []string{"created_at", "updated_at"}
	workTagPrimaryKeyColumns     = []string{"id"}
	workTagGeneratedColumns      = []string{}
)

type (
	// WorkTagSlice is an alias for a slice of pointers to WorkTag.
	// This should almost always be used instead of []WorkTag.
	WorkTagSlice []*WorkTag
	// WorkTagHook is the signature for custom WorkTag hook methods
	WorkTagHook func(context.Context, boil.ContextExecutor, *WorkTag) error

	workTagQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workTagType                 = reflect.TypeOf(&WorkTag{})
	workTagMapping              = queries.MakeStructMapping(workTagType)
	workTagPrimaryKeyMapping, _ = queries.BindMapping(workTagType, workTagMapping, workTagPrimaryKeyColumns)
	workTagInsertCacheMut       sync.RWMutex
	workTagInsertCache          = make(map[string]insertCache)
	workTagUpdateCacheMut       sync.RWMutex
	workTagUpdateCache          = make(map[string]updateCache)
	workTagUpsertCacheMut       sync.RWMutex
	workTagUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workTagAfterSelectMu sync.Mutex
var workTagAfterSelectHooks []WorkTagHook

var workTagBeforeInsertMu sync.Mutex
var workTagBeforeInsertHooks []WorkTagHook
var workTagAfterInsertMu sync.Mutex
var workTagAfterInsertHooks []WorkTagHook

var workTagBeforeUpdateMu sync.Mutex
var workTagBeforeUpdateHooks []WorkTagHook
var workTagAfterUpdateMu sync.Mutex
var workTagAfterUpdateHooks []WorkTagHook

var workTagBeforeDeleteMu sync.Mutex
var workTagBeforeDeleteHooks []WorkTagHook
var workTagAfterDeleteMu sync.Mutex
var workTagAfterDeleteHooks []WorkTagHook

var workTagBeforeUpsertMu sync.Mutex
var workTagBeforeUpsertHooks []WorkTagHook
var workTagAfterUpsertMu sync.Mutex
var workTagAfterUpsertHooks []WorkTagHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkTag) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkTag) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkTag) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkTag) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkTag) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkTag) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkTag) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkTag) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkTag) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workTagAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkTagHook registers your hook function for all future operations.
func AddWorkTagHook(hookPoint boil.HookPoint, workTagHook WorkTagHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workTagAfterSelectMu.Lock()
		workTagAfterSelectHooks = append(workTagAfterSelectHooks, workTagHook)
		workTagAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workTagBeforeInsertMu.Lock()
		workTagBeforeInsertHooks = append(workTagBeforeInsertHooks, workTagHook)
		workTagBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workTagAfterInsertMu.Lock()
		workTagAfterInsertHooks = append(workTagAfterInsertHooks, workTagHook)
		workTagAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workTagBeforeUpdateMu.Lock()
		workTagBeforeUpdateHooks = append(workTagBeforeUpdateHooks, workTagHook)
		workTagBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workTagAfterUpdateMu.Lock()
		workTagAfterUpdateHooks = append(workTagAfterUpdateHooks, workTagHook)
		workTagAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workTagBeforeDeleteMu.Lock()
		workTagBeforeDeleteHooks = append(workTagBeforeDeleteHooks, workTagHook)
		workTagBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workTagAfterDeleteMu.Lock()
		workTagAfterDeleteHooks = append(workTagAfterDeleteHooks, workTagHook)
		workTagAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workTagBeforeUpsertMu.Lock()
		workTagBeforeUpsertHooks = append(workTagBeforeUpsertHooks, workTagHook)
		workTagBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workTagAfterUpsertMu.Lock()
		workTagAfterUpsertHooks = append(workTagAfterUpsertHooks, workTagHook)
		workTagAfterUpsertMu.Unlock()
	}
}

// One returns a single workTag record from the query.
func (q workTagQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkTag, error) {
	o := &WorkTag{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for work_tags")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkTag records from the query.
func (q workTagQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkTagSlice, error) {
	var o []*WorkTag

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WorkTag slice")
	}

	if len(workTagAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkTag records in the query.
func (q workTagQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count work_tags rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workTagQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if work_tags exists")
	}

	return count > 0, nil
}

// WorkHavingTags retrieves all the work_having_tag's WorkHavingTags with an executor.
func (o *WorkTag) WorkHavingTags(mods ...qm.QueryMod) workHavingTagQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`work_having_tags`.`work_tag_id`=?", o.ID),
	)

	return WorkHavingTags(queryMods...)
}

// LoadWorkHavingTags allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workTagL) LoadWorkHavingTags(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkTag interface{}, mods queries.Applicator) error {
	var slice []*WorkTag
	var object *WorkTag

	if singular {
		var ok bool
		object, ok = maybeWorkTag.(*WorkTag)
		if !ok {
			object = new(WorkTag)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkTag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkTag))
			}
		}
	} else {
		s, ok := maybeWorkTag.(*[]*WorkTag)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkTag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkTag))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &workTagR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workTagR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`work_having_tags`),
		qm.WhereIn(`work_having_tags.work_tag_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load work_having_tags")
	}

	var resultSlice []*WorkHavingTag
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice work_having_tags")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on work_having_tags")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for work_having_tags")
	}

	if len(workHavingTagAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkHavingTags = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workHavingTagR{}
			}
			foreign.R.WorkTag = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorkTagID {
				local.R.WorkHavingTags = append(local.R.WorkHavingTags, foreign)
				if foreign.R == nil {
					foreign.R = &workHavingTagR{}
				}
				foreign.R.WorkTag = local
				break
			}
		}
	}

	return nil
}

// AddWorkHavingTags adds the given related objects to the existing relationships
// of the work_tag, optionally inserting them as new records.
// Appends related to o.R.WorkHavingTags.
// Sets related.R.WorkTag appropriately.
func (o *WorkTag) AddWorkHavingTags(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkHavingTag) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkTagID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `work_having_tags` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"work_tag_id"}),
				strmangle.WhereClause("`", "`", 0, workHavingTagPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkTagID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workTagR{
			WorkHavingTags: related,
		}
	} else {
		o.R.WorkHavingTags = append(o.R.WorkHavingTags, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workHavingTagR{
				WorkTag: o,
			}
		} else {
			rel.R.WorkTag = o
		}
	}
	return nil
}

// WorkTags retrieves all the records using an executor.
func WorkTags(mods ...qm.QueryMod) workTagQuery {
	mods = append(mods, qm.From("`work_tags`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`work_tags`.*"})
	}

	return workTagQuery{q}
}

// FindWorkTag retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkTag(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkTag, error) {
	workTagObj := &WorkTag{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `work_tags` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workTagObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from work_tags")
	}

	if err = workTagObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workTagObj, err
	}

	return workTagObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkTag) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no work_tags provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workTagColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workTagInsertCacheMut.RLock()
	cache, cached := workTagInsertCache[key]
	workTagInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workTagAllColumns,
			workTagColumnsWithDefault,
			workTagColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workTagType, workTagMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workTagType, workTagMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `work_tags` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `work_tags` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `work_tags` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, workTagPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into work_tags")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for work_tags")
	}

CacheNoHooks:
	if !cached {
		workTagInsertCacheMut.Lock()
		workTagInsertCache[key] = cache
		workTagInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkTag.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkTag) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workTagUpdateCacheMut.RLock()
	cache, cached := workTagUpdateCache[key]
	workTagUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workTagAllColumns,
			workTagPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update work_tags, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `work_tags` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, workTagPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workTagType, workTagMapping, append(wl, workTagPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update work_tags row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for work_tags")
	}

	if !cached {
		workTagUpdateCacheMut.Lock()
		workTagUpdateCache[key] = cache
		workTagUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workTagQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for work_tags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for work_tags")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkTagSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `work_tags` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workTagPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in workTag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all workTag")
	}
	return rowsAff, nil
}

var mySQLWorkTagUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkTag) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no work_tags provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workTagColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLWorkTagUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workTagUpsertCacheMut.RLock()
	cache, cached := workTagUpsertCache[key]
	workTagUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workTagAllColumns,
			workTagColumnsWithDefault,
			workTagColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workTagAllColumns,
			workTagPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert work_tags, could not build update column list")
		}

		ret := strmangle.SetComplement(workTagAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`work_tags`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `work_tags` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(workTagType, workTagMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workTagType, workTagMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for work_tags")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(workTagType, workTagMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for work_tags")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for work_tags")
	}

CacheNoHooks:
	if !cached {
		workTagUpsertCacheMut.Lock()
		workTagUpsertCache[key] = cache
		workTagUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkTag record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkTag) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WorkTag provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workTagPrimaryKeyMapping)
	sql := "DELETE FROM `work_tags` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from work_tags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for work_tags")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workTagQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no workTagQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from work_tags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for work_tags")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkTagSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workTagBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `work_tags` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workTagPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from workTag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for work_tags")
	}

	if len(workTagAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkTag) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkTag(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkTagSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkTagSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `work_tags`.* FROM `work_tags` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, workTagPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WorkTagSlice")
	}

	*o = slice

	return nil
}

// WorkTagExists checks if the WorkTag row exists.
func WorkTagExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `work_tags` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if work_tags exists")
	}

	return exists, nil
}

// Exists checks if the WorkTag row exists.
func (o *WorkTag) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkTagExists(ctx, exec, o.ID)
}
